version: '3'

services:
  db_messengers:
    image: postgres:9.6-alpine
    environment:
    - POSTGRES_DB=db_messengers
    - POSTGRES_USER=messengers
    - POSTGRES_PASSWORD=PwD34451DeV
    volumes:
      - ./docker/pg_data:/var/lib/postgresql/data
    ports:
    - 8511:5432

  php_messengers:
    build: docker/php
    container_name: php_messengers
    restart: always
    tty: true
    volumes:
    - .:/srv/messengers-test:delegated
    ports:
    - 8500:9000
    - 8501:9001

  nginx-messengers:
    image: nginx:latest
    depends_on:
    - php_messengers
    volumes:
    - .:/srv/messengers-test
    - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    ports:
    - 8510:80